Demo_19_NovMVC/Models/ErrorViewModel.cs
using System;

namespace Demo_19_NovMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Demo_19_NovMVC/Models/Produit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Demo_19_NovMVC.Models
{
  [Table("PRODUIT")]
    public class Produit
    {
         [Key]
        public int ProduitID { get; set; }
        [Required]
        [MinLength(10), MaxLength(30)]
        public string Description { get; set; }
        [Required]
        [Range(100, 2000)]
        public double Prix { get; set; }
    }
}

Demo_19_NovMVC/Controllers/HomeController.cs
using Demo_19_NovMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Demo_19_NovMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Demo_19_NovMVC/Controllers/ProduitController.cs
using Demo_19_NovMVC.Data;
using Demo_19_NovMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo_19_NovMVC.Controllers
{
    public class ProduitController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ProduitController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Produit> ListProd = _db.Produits;
            return View(ListProd);
        }

        // Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Produit p)
        {
            if (ModelState.IsValid)
            {
                _db.Produits.Add(p);
                _db.SaveChanges();
                TempData["success"] = " le produit a été créé avec succes";
                return RedirectToAction("Index");
            }

            return View(p);
        }

        // Edit
        [HttpGet]
        public IActionResult Edit(int ? id)
        {
            if (id ==0 || id ==null)
            {
                return NotFound();
            }
            Produit p = _db.Produits.SingleOrDefault(p => p.ProduitID ==id);
            if (p ==null)
            {
                return NotFound();

            }
            return View(p);
        }

        [HttpPost]
        public IActionResult Edit(Produit p)
        {
            if (ModelState.IsValid)
            {
                _db.Produits.Update(p);
                _db.SaveChanges();
                TempData["success"] = " le produit a été modifié avec succes";

                return RedirectToAction("Index");
            }

            return View(p);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            Produit p = _db.Produits.SingleOrDefault(p => p.ProduitID == id);
            if (p == null)
            {
                return NotFound();

            }
            return View(p);
        }

        [HttpPost]
        public IActionResult Delete(Produit p)
        {
            var deletedP = _db.Produits.Find(p.ProduitID);

            if (deletedP !=null)
            {
                _db.Produits.Remove(deletedP);
                _db.SaveChanges();
                TempData["success"] = " le produit a été supprimé avec succes";

                return RedirectToAction("Index");
            }

            return View(deletedP);
        }
    }
}

Demo_19_NovMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Demo_19_NovMVC/Views/Produit/Create.cshtml
@model Produit
@{
    ViewData["Title"] = "Create";
}

<br />
<form method="post" action="Create">
    <div class="border pt-3 p-3">

        <div class="row pb-3 p-3">
             <h4 class="text-primary">Create</h4>
            <hr />
        </div>

        <div class="pb-3">
            <label>Description</label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>

        </div>

        <div class="pb-3">
            <label>Prix</label>
            <input asp-for="Prix" class="form-control" />
            <span asp-validation-for="Prix" class="text-danger"></span>

        </div>

        <button type="submit"  class="btn btn-success mx-1 " style="width: 150px">Create</button>
        <a asp-controller="Produit" asp-action="Index" class="btn btn-secondary mx-1 " style="width: 150px">BackToList</a>


    </div>

</form>

Demo_19_NovMVC/Views/Produit/Delete.cshtml
@model Produit
@{
    ViewData["Title"] = "Delete";
}




<h4 class="text-danger">Etes vous sure de vouloir supprimer cet objet></h4>

<form method="post" asp-action="Delete">
        <input asp-for="ProduitID" hidden />
    <div class="border pt-3 p-3">
        <div class="pb-3">
            <label>Description</label>
            <input asp-for="Description" disabled class="form-control" />

        </div>

        <div class="pb-3">
            <label>Prix</label>
            <input asp-for="Prix" disabled class="form-control" />

        </div>

        <button type="submit" class="btn btn-danger mx-1 " style="width: 150px">Delete</button>
        @*<a asp-controller="Produit" asp-action="DeletPost" asp-route="@ProduiID" class="btn btn-danger mx-1 " style="width: 150px">Delete</a>*@

        <a asp-controller="Produit" asp-action="Index" class="btn btn-secondary mx-1 " style="width: 150px">BackToList</a>


    </div>

</form>

Demo_19_NovMVC/Views/Produit/Edit.cshtml
@model Produit
@{
    ViewData["Title"] = "Edit";
}

<h4 class="text-primary">Edit</h4>

<form method="post" action="Edit">
    <div class="border pt-3 p-3">
        <div class="pb-3">
            <label>Description</label>
            <input asp-for="Description" class="form-control" />

        </div>

        <div class="pb-3">
            <label>Prix</label>
            <input asp-for="Prix" class="form-control" />

        </div>

        <button type="submit" class="btn btn-success mx-1 " style="width: 150px">Update</button>
        <a asp-controller="Produit" asp-action="Index" class="btn btn-secondary mx-1 " style="width: 150px">BackToList</a>


    </div>

</form>

Demo_19_NovMVC/Views/Produit/Index.cshtml
@model IEnumerable<Demo_19_NovMVC.Models.Produit>


@{
    ViewData["Title"] = "Index";
}

@if(TempData["success"] !=null) { 
    <h4 class="text-success">@TempData["success"]</h4>
}

<div class="container p-3">
    <div class="row pt-4 pb">
        <div class="col-6">
            <h4 class="text-primary">Liste des Produit</h4>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Produit" asp-action="Create" class="btn btn-success"><i class="bi bi-plus-circle"></i>&nbsp;Create</a>
        </div>
    </div>


    <br />



    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr class="text-center">
                    <th>Produit ID</th>
                    <th>Description</th>
                    <th>Prix</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr class="text-center">
                        <td>@obj.ProduitID</td>
                        <td>@obj.Description</td>
                        <td>@obj.Prix</td>
                        <td class="w-100 btn-group" role="group">
                            <a asp-controller="Produit" asp-action="Edit" asp-route-id="@obj.ProduitID" class="btn btn-primary mx-1"><i class="bi bi-pencil-square"></i></a>
                            <a asp-controller="Produit" asp-action="Delete" asp-route-id="@obj.ProduitID" class="btn btn-danger mx-1 "><i class="bi bi-trash-fill"></i></a>

                        </td>

                    </tr>
                }
            </tbody>
        </table>
    }

</div>

Demo_19_NovMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo_19_NovMVC</title>
    <link rel="stylesheet" href="~/css/BootsTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Produit" asp-action="Index">Produit</a>

                        </li>
                       
                        @*<li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>*@
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>



       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted bg-dark">
        <div class="container">
            &copy; 2021 - Demo_19_NovMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>